# Generated by Django 5.2.7 on 2025-10-31 13:51

from django.db import migrations


def seed_item_categories(apps, schema_editor):
    ItemCategory = apps.get_model('menu', 'ItemCategory')
    default_categories = [
        ('Starters', 'Appetizers and light dishes to begin your meal.'),
        ('Main Dishes', 'Hearty and filling main course selections.'),
        ('Desserts', 'Sweet treats and pastries.'),
        ('Drinks', 'Beverages and refreshments.'),
        ('Specials', 'Limited-time or chef-recommended dishes.')
    ]

    for name, description in default_categories:
        ItemCategory.objects.get_or_create(name=name, defaults={'description': description})


def unseed_item_categories(apps, schema_editor):
    ItemCategory = apps.get_model('menu', 'ItemCategory')
    names = ['Starters', 'Main Dishes', 'Desserts', 'Drinks', 'Specials']
    ItemCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_item_categories, reverse_code=unseed_item_categories),
    ]
