# Generated by Django 5.2.7 on 2025-10-31 14:06

from django.db import migrations


def seed_initial_menu_version(apps, schema_editor):
    ItemCategory = apps.get_model('menu', 'ItemCategory')
    Item = apps.get_model('menu', 'Item')
    MenuVersion = apps.get_model('menu', 'MenuVersion')
    MenuItem = apps.get_model('menu', 'MenuItem')

    # 1. Fetch existing categories (seeded earlier)
    categories = {c.name: c for c in ItemCategory.objects.all()}

    # 2. Create base items
    items_data = [
        ('Omelette with cottage cheese and herbs', 'A light, fluffy omelette with herbs.', 9.00, 'Starters'),
        ('Avocado toast with poached egg', 'Toasted bread with avocado and a perfectly poached egg.', 10.50, 'Main Dishes'),
        ('Classic syrniki with sour cream', 'Traditional cottage cheese pancakes served with cream.', 8.40, 'Desserts'),
        ('Oatmeal with berries and honey', 'Healthy oatmeal topped with fresh berries and honey.', 12.00, 'Desserts'),
        ('Fresh orange juice', '100% squeezed orange juice.', 6.50, 'Drinks'),
    ]

    items = []
    for name, desc, price, cat_name in items_data:
        category = categories.get(cat_name)
        if not category:
            continue
        item, _ = Item.objects.get_or_create(
            name=name,
            defaults={
                'description': desc,
                'base_unit_price': price,
                'category': category,
            },
        )
        items.append(item)

    # 3. Create initial menu version (v1)
    menu_version, _ = MenuVersion.objects.get_or_create(
        name='Initial Menu',
        version_no=1,
        defaults={'is_active': True},
    )

    # 4. Link menu items
    for item in items:
        MenuItem.objects.get_or_create(
            menu_version=menu_version,
            item=item,
            defaults={
                'name': item.name,
                'description': item.description,
                'unit_price': item.base_unit_price,
                'category': item.category,
            },
        )


def unseed_initial_menu_version(apps, schema_editor):
    Item = apps.get_model('menu', 'Item')
    MenuVersion = apps.get_model('menu', 'MenuVersion')
    MenuItem = apps.get_model('menu', 'MenuItem')

    MenuItem.objects.all().delete()
    MenuVersion.objects.all().delete()
    Item.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_item_image"),
    ]

    operations = [
        migrations.RunPython(seed_initial_menu_version, reverse_code=unseed_initial_menu_version),
    ]
