# Generated by Django 5.2.7 on 2025-10-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_seed_initial_menu_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="is_deleted",
        ),
    ]
