# Generated by Django 5.2.7 on 2025-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_remove_menuitem_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuversion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
