# Generated by Django 5.2.7 on 2025-10-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_menuversion_deleted_at_menuversion_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="name",
        ),
    ]
