# Generated by Django 5.2.7 on 2025-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_remove_menuitem_description_remove_menuitem_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
    ]
