# Generated by Django 5.2.7 on 2025-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestprofile",
            name="chat_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
