# Generated by Django 5.2.7 on 2025-11-01 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.CharField(max_length=10, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="table",
            name="qr_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="QR UUID"
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("OCCUPIED", "Occupied"),
                    ("NEEDS_HELP", "Needs Help"),
                ],
                default="FREE",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="assistance_requested",
            field=models.BooleanField(
                default=False, verbose_name="assistance requested"
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="closed at"),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="opened_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="opened at"),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opened_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="opened by",
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                default="OPEN",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="tablesession",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="table.table",
                verbose_name="table",
            ),
        ),
        migrations.AlterModelTable(
            name="table",
            table=None,
        ),
    ]
